<?php

namespace zvook\Skrill\Models;

use zvook\Skrill\Components\AsArrayTrait;

/**
 * @package zvook\Skrill\Models
 * @author Dmitry zvook Klyukin
 * @see https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf#G4.1035703
 */
class SkrillStatusResponse extends Model
{
    const STATUS_PROCESSED = 2;
    const STATUS_FAILED = -2;
    const STATUS_PENDING = 0;
    const STATUS_CANCELED = -1;
    const STATUS_CHARGEBACK = -3;

    use AsArrayTrait;

    /**
     * Your email address.
     *
     * @var string
     * @required true
     */
    protected $pay_to_email;

    /**
     * Email address of the customer who is making the payment.
     * Note if a Skrill wallet account exists with this email and the Skrill Wallet is one of the available
     * payment method tabs then it will be selected as the default payment method.
     *
     * @var string
     * @required true
     */
    protected $pay_from_email;

    /**
     * Unique ID of your Skrill account. ONLY needed for the calculation of the MD5 signature.
     *
     * @var string
     * @required true
     */
    protected $merchant_id;

    /**
     * Skrill's internal unique reference ID for this transaction.
     *
     * @var string
     * @required true
     */
    protected $mb_transaction_id;

    /**
     * Amount of the payment as posted in HTML form
     *
     * @var int|float
     * @required true
     */
    protected $amount;

    /**
     * The total amount of the payment in the currency of your merchant Skrill digital wallet account.
     *
     * @var int|float
     * @required true
     */
    protected $mb_amount;

    /**
     * Amount of the amount as posted in HTML form
     *
     * @var string
     * @required true
     */
    protected $currency;

    /**
     * Currency of mb_amount . Will always be the same as the currency of your merchant Skrill digital wallet account.
     *
     * @var string
     * @required true
     */
    protected $mb_currency;

    /**
     * Status of the transaction
     *
     * @var int
     * @required true
     */
    protected $status;

    /**
     * MD5 signature
     *
     * @var string
     * @required true
     * @see https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf#M10.9.97017.heading.2.63.MD5.signature
     */
    protected $md5sig;

    /**
     * SHA2 signature
     *
     * @var string
     * @required true
     * @see https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf#M10.9.75080.heading.2.64.SHA2.signature
     */
    protected $sha2sig;

    /**
     * If the customer pays using a Skrill Wallet, this is the unique ID of their Skrill account.
     * If the customer pays with any other payment method, then this is a unique ID for this payment generated by Skril.
     *
     * @var string
     * @required false
     */
    protected $customer_id = null;

    /**
     * A unique reference or identification number provided by you in your HTML form.
     *
     * @var string
     * @required false
     */
    protected $transaction_id = null;

    /**
     * If the transaction has a status value ‐ 2 (failed),
     * this field will contain a code detailing the reason for the failure.
     * Note that you will need to ask Skrill to enable this feature to receive the code
     *
     * @var string
     * @required false
     */
    protected $failed_reason_code = null;

    /**
     * The payment method the customer used. Contact merchant services to enable this option.
     *
     * @var string
     * @required false
     * @see https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf#G4.1035703
     */
    protected $payment_type = null;

    /**
     * If you submitted a list of values in the merchant_fields parameter,
     * they will be passed back with the status report.
     *
     * @var string
     * @required false
     */
    protected $merchant_fields = null;

    /**
     * @var string
     * @required false
     * @see https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf#G4.1035971
     */
    protected $payment_instrument_country = null;

    /**
     * @var string
     * @required false
     * @see https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf#G4.1035971
     */
    protected $country = null;

    /**
     * @var string
     * @required false
     * @see https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf#G4.1035971
     */
    protected $IP_country = null;

    /**
     * @return string
     */
    public function getPayToEmail()
    {
        return $this->pay_to_email;
    }

    /**
     * @return string
     */
    public function getPayFromEmail()
    {
        return $this->pay_from_email;
    }

    /**
     * @return string
     */
    public function getMerchantId()
    {
        return $this->merchant_id;
    }

    /**
     * @return string
     */
    public function getMbTransactionId()
    {
        return $this->mb_transaction_id;
    }

    /**
     * @return float|int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @return float|int
     */
    public function getMbAmount()
    {
        return $this->mb_amount;
    }

    /**
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * @return string
     */
    public function getMbCurrency()
    {
        return $this->mb_currency;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return string
     */
    public function getMd5sig()
    {
        return $this->md5sig;
    }

    /**
     * @return string
     */
    public function getSha2sig()
    {
        return $this->sha2sig;
    }

    /**
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }

    /**
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * @return string
     */
    public function getFailedReasonCode()
    {
        return $this->failed_reason_code;
    }

    /**
     * @return string
     */
    public function getPaymentType()
    {
        return $this->payment_type;
    }

    /**
     * @return string
     */
    public function getMerchantFields()
    {
        return $this->merchant_fields;
    }

    /**
     * @return string
     */
    public function getPaymentInstrumentCountry()
    {
        return $this->payment_instrument_country;
    }

    /**
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @return string
     */
    public function getIPCountry()
    {
        return $this->IP_country;
    }

    /**
     * @return bool
     */
    public function isProcessed()
    {
        return $this->status == self::STATUS_PROCESSED;
    }

    /**
     * @return bool
     */
    public function isFailed()
    {
        return $this->status == self::STATUS_FAILED;
    }

    /**
     * @return bool
     */
    public function isCanceled()
    {
        return $this->status == self::STATUS_CANCELED;
    }

    /**
     * @return bool
     */
    public function isPending()
    {
        return $this->status == self::STATUS_PENDING;
    }

    /**
     * @return bool
     */
    public function isChargeBack()
    {
        return $this->status == self::STATUS_CHARGEBACK;
    }

    /**
     * You can find your secret word in Skrill account
     * Returns whether the Skrill response valid
     * @param $secretWord
     * @return bool
     */
    public function verifySignature($secretWord)
    {
        $digest = strtoupper(md5(implode('', [
            $this->getMerchantId(),
            $this->getTransactionId(),
            strtoupper(md5($secretWord)),
            $this->getMbAmount(),
            $this->getMbCurrency(),
            $this->getStatus()
        ])));

        return $digest == $this->getMd5sig();
    }

    /**
     * @param $targetPath
     * @return int
     */
    public function log($targetPath)
    {
        $log = date('d M y H:i:s', time());
        $log .= '| ' . json_encode($this->asArray()) . "\n\n";

        return file_put_contents($targetPath, $log, FILE_APPEND);
    }
}