<?php

declare(strict_types=1);

namespace Xaerobiont\Skrill;

/**
 * @see https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf
 */
class StatusResponse extends Model implements StatusResponseInterface
{
    const STATUS_PROCESSED = 2;
    const STATUS_FAILED = -2;
    const STATUS_PENDING = 0;
    const STATUS_CANCELED = -1;
    const STATUS_CHARGEBACK = -3;

    /**
     * Your email address.
     */
    protected string $pay_to_email;

    /**
     * Email address of the customer who is making the payment.
     * Note if a Skrill wallet account exists with this email and the Skrill Wallet is one of the available
     * payment method tabs then it will be selected as the default payment method.
     */
    protected string $pay_from_email;

    /**
     * Unique ID of your Skrill account. ONLY needed for the calculation of the MD5 signature.
     */
    protected mixed $merchant_id;

    /**
     * If the customer pays using a Skrill Wallet, this is the unique ID of their Skrill account.
     * If the customer pays with any other payment method, this is a unique ID for this payment generated by Skrill.
     */
    protected mixed $customer_id = null;

    /**
     * Transaction ID provided by your request.
     * If no transaction_id has submitted, the mb_transaction_id value will be here.
     */
    protected mixed $transaction_id = null;

    /**
     * Skrill's internal unique reference ID for this transaction.
     */
    protected mixed $mb_transaction_id;

    /**
     * Amount of the payment as posted in HTML form
     */
    protected int|float $amount;

    /**
     * The total amount of the payment in the currency of your merchant Skrill digital wallet account.
     */
    protected int|float $mb_amount;

    /**
     * Amount of the amount as posted in HTML form
     */
    protected string $currency;

    /**
     * Currency of mb_amount . Will always be the same as the currency of your merchant Skrill digital wallet account.
     */
    protected string $mb_currency;

    /**
     * Status of the transaction
     */
    protected int $status;

    /**
     * If the transaction has a status value -2 (failed), this field will contain a code detailing the reason for the failure.
     * Note that you will need to ask Skrill to enable this feature to receive the code.
     */
    protected mixed $failed_reason_code = null;

    /**
     * MD5 signature
     */
    protected string $md5sig;

    /**
     * SHA2 signature
     */
    protected ?string $sha2sig = null;

    /**
     * If the Neteller payment method is used this parameter contains the Neteller customer’s account id or email
     * depending on the details entered by the Neteller customer or the value supplied in the neteller_account parameter.
     */
    protected mixed $neteller_id = null;

    /**
     * The payment method the customer used. Contact merchant services to enable this option.
     */
    protected mixed $payment_type = null;

    /**
     * If you submitted a list of values in the merchant_fields parameter, they will be passed back with the status report.
     */
    protected mixed $merchant_fields = null;

    /**
     * You can find your secret word in Skrill account
     * Returns whether the Skrill response valid
     */
    public function verifySignature(string $secretWord): bool
    {
        $digest = strtoupper(md5(implode('', [
            $this->getMerchantId(),
            $this->getTransactionId(),
            strtoupper(md5($secretWord)),
            $this->getMbAmount(),
            $this->getMbCurrency(),
            $this->getStatus(),
        ])));

        return $digest === $this->getMd5sig();
    }

    public function getPayToEmail(): string
    {
        return $this->pay_to_email;
    }

    public function getPayFromEmail(): string
    {
        return $this->pay_from_email;
    }

    public function getMerchantId(): mixed
    {
        return $this->merchant_id;
    }

    public function getCustomerId(): mixed
    {
        return $this->customer_id;
    }

    public function getTransactionId(): mixed
    {
        return $this->transaction_id;
    }

    public function getMbTransactionId(): mixed
    {
        return $this->mb_transaction_id;
    }

    public function getAmount(): float|int
    {
        return $this->amount;
    }

    public function getMbAmount(): float|int
    {
        return $this->mb_amount;
    }

    public function getCurrency(): string
    {
        return $this->currency;
    }

    public function getMbCurrency(): string
    {
        return $this->mb_currency;
    }

    public function getStatus(): int
    {
        return $this->status;
    }

    public function getFailedReasonCode(): mixed
    {
        return $this->failed_reason_code;
    }

    public function getMd5sig(): string
    {
        return $this->md5sig;
    }

    public function getSha2sig(): ?string
    {
        return $this->sha2sig;
    }

    public function getNetellerId(): mixed
    {
        return $this->neteller_id;
    }

    public function getPaymentType(): mixed
    {
        return $this->payment_type;
    }

    public function getMerchantFields(): mixed
    {
        return $this->merchant_fields;
    }
}